Adding Italian translation
tedsalmon/BlueBus pull request #75
Opened 2021-07-21 14:36 UTC by bcagnoni

I've just copy-pasted from LOCALE_LANG_ENGLISH and translated it.
I understand Settings > XXXXXXXXX strings can be longer that 15 char I hope mine aren't too long
I also updated the switch at the bottom reproducing the same logic

2021-07-24 19:51 UTC, DeSchmiddi requested changes
Hello there, I have no idea about if the Code is fine, but I believe that "Calling" (l. 80 en. orig.) should be tranlated "chiamando" instead of "Chiamate" (l. 19 merge file), which means calls, as far as I know (not a native speaker). I didn't find anything else that was strange in the translation, but someone should definetly look over the code, as I don't feel qualified.

2021-07-25 00:57 UTC, tedsalmon commented
@DeSchmiddi

@bcagnoni is Italian, I believe. I'll leave it up to him, but I do appreciate the feedback!

-Ted

2021-07-26 08:22 UTC, bcagnoni commented
@tedsalmon Yes I'm Italian.
@DeSchmiddi thanks for the feedback. You are right and litteral translation is _Chiamando_ - it's the gerundive form - but in current Italian would sound weird. I've been thinking about it because it could be translated differently depending on the context. In this case my understanding is: Settings > Calling means settings related to calls. Make sense?

I've also checked how Apple does it with iPhone and everytime there is _calls_ under settings it's translated with _chiamate_.

Battista

2021-07-26 11:28 UTC, DeSchmiddi commented
Absolutely. That's good to know! Thanks!

2021-11-09 01:51 UTC, tedsalmon approved these changes

2021-11-09 01:52 UTC, merged